import 'package:path_provider/path_provider.dart';
import 'package:powersync/powersync.dart';
import 'package:path/path.dart';

// Define column types as constants for reusability
const ColumnType uuidType =
    ColumnType.text; // 'TEXT'; // UUIDs are stored as text in SQLite
const ColumnType integerType = ColumnType.integer; // 'INTEGER';
const ColumnType decimalType = ColumnType.real; // 'INTEGER';
const ColumnType textType = ColumnType.text; //'TEXT';
const ColumnType booleanType =
    ColumnType.integer; //'INTEGER'; // SQLite uses 0/1 for booleans
const ColumnType timestampType =
    ColumnType.text; //'TEXT'; // ISO 8601 strings for timestamps
const Schema schema = Schema([
  Table('res_currency', [
    Column('id', uuidType),
    Column('name', textType),
    Column('symbol', textType),
    Column('rounding', integerType),
    Column('decimal_places', integerType),
    Column('active', booleanType),
    Column('create_date', timestampType),
    Column('write_date', timestampType),
  ]),
  Table('res_currency_rate', [
    Column('id', uuidType),
    Column('currency_id', uuidType),
    Column('rate', decimalType),
    Column('date', timestampType),
    Column('company_id', uuidType),
  ]),
  Table('res_company', [
    Column('id', uuidType),
    Column('name', textType),
    Column('currency_id', uuidType),
    Column('create_date', timestampType),
    Column('write_date', timestampType),
    Column('active', booleanType),
  ]),
  Table('res_user', [
    Column('id', uuidType),
    Column('company_id', uuidType),
    Column('login', textType),
    Column('password', textType),
    Column('name', textType),
    Column('email', textType),
    Column('language_code', textType),
    Column('active', booleanType),
    Column('create_date', timestampType),
    Column('write_date', timestampType),
  ]),
  Table('res_role', [
    Column('id', uuidType),
    Column('company_id', uuidType),
    Column('name', textType),
    Column('description', textType),
    Column('active', booleanType),
    Column('create_date', timestampType),
    Column('write_date', timestampType),
  ]),
  Table('res_user_role_link', [
    Column('id', uuidType),
    Column('user_id', uuidType),
    Column('role_id', uuidType),
    Column('create_date', timestampType),
    Column('write_date', timestampType),
  ]),
  Table('res_permission', [
    Column('id', uuidType),
    Column('company_id', uuidType),
    Column('name', textType),
    Column('model', textType),
    Column('create_date', timestampType),
    Column('write_date', timestampType),
  ]),
  Table('res_role_permission_link', [
    Column('id', uuidType),
    Column('role_id', uuidType),
    Column('permission_id', uuidType),
    Column('create_date', timestampType),
    Column('write_date', timestampType),
  ]),
  Table('res_partner', [
    Column('id', uuidType),
    Column('company_id', uuidType),
    Column('currency_id', uuidType),
    Column('parent_id', uuidType),
    Column('name', textType),
    Column('nick_name', textType),
    Column('profile_picture', textType),
    Column('email', textType),
    Column('phone', textType),
    Column('is_company', booleanType),
    Column('is_customer', booleanType),
    Column('is_vendor', booleanType),
    Column('create_date', timestampType),
    Column('write_date', timestampType),
    Column('active', booleanType),
    Column('pricelist_id', uuidType),
  ]),
  Table('product_category', [
    Column('id', uuidType),
    Column('company_id', uuidType),
    Column('name', textType),
    Column('parent_id', uuidType),
    Column('create_date', timestampType),
    Column('write_date', timestampType),
    Column('active', booleanType),
  ]),
  Table('res_uom', [
    Column('id', uuidType),
    Column('unit_name', textType),
    Column('unit_symbol', textType),
    Column('unit_type', textType),
    Column('base_unit_id', uuidType),
    Column('conversion_factor', decimalType),
    Column('is_active', booleanType),
    Column('created_at', timestampType),
  ]),
  Table('product_template', [
    Column('id', uuidType),
    Column('company_id', uuidType),
    Column('category_id', uuidType),
    Column('default_code', textType),
    Column('barcode', textType),
    Column('sale_uom_id', uuidType),
    Column('purchase_uom_id', uuidType),
    Column('weight_uom_id', uuidType),
    Column('create_date', timestampType),
    Column('write_date', timestampType),
    Column('is_weighable', booleanType),
    Column('brand_name', textType),
    Column('print_override', booleanType),
    Column('printer_name', textType),
    Column('internal_note', textType),
    Column('sales_note', textType),
    Column('sale_ok', booleanType),
    Column('number_of_variants', integerType),
  ]),
  Table('product_product', [
    Column('id', uuidType),
    Column('company_id', uuidType),
    Column('category_id', uuidType),
    Column('template_id', uuidType),
    Column('name', textType),
    Column('uom_id', uuidType),
    Column('weight_uom_id', uuidType),
    Column('default_code', textType),
    Column('barcode', textType),
    Column('list_price', integerType),
    Column('standard_price', integerType),
    Column('type', textType),
    Column('create_date', timestampType),
    Column('write_date', timestampType),
    Column('active', booleanType),
    Column('discontinued', booleanType),
    Column('sku', textType),
    Column('image', textType),
    Column('stock', integerType),
    Column('base_scan_points', integerType),
  ]),
  Table('product_pricelist', [
    Column('id', uuidType),
    Column('name', textType),
    Column('currency', textType),
  ]),
  Table('product_pricelist_item', [
    Column('id', uuidType),
    Column('pricelist_id', uuidType),
    Column('product_id', uuidType),
    Column('compute_price', textType),
    Column('min_quantity', integerType),
    Column('max_quantity', integerType),
    Column('fixed_price', integerType),
    Column('percentage_discount', integerType),
    Column('formula_expression', textType),
    Column('min_margin', integerType),
    Column('max_margin', integerType),
  ]),
  Table('quotation', [
    Column('id', uuidType),
    Column('company_id', uuidType),
    Column('partner_id', uuidType),
    Column('currency_id', uuidType),
    Column('reference_number', textType),
    Column('invoice_date', timestampType),
    Column('due_date', timestampType),
    Column('status', textType),
    Column('amount_total', integerType),
    Column('pricelist_id', uuidType),
    Column('create_date', timestampType),
    Column('write_date', timestampType),
  ]),
  Table('quotation_item', [
    Column('id', uuidType),
    Column('quotation_id', uuidType),
    Column('company_id', uuidType),
    Column('product_id', uuidType),
    Column('quantity', integerType),
    Column('unit_price', integerType),
    Column('discount', integerType),
    Column('price_subtotal', integerType),
    Column('uom_id', uuidType),
    Column('weight_uom_id', uuidType),
    Column('weight', decimalType),
  ]),
  Table('account_invoice', [
    Column('id', uuidType),
    Column('company_id', uuidType),
    Column('partner_id', uuidType),
    Column('currency_id', uuidType),
    Column('invoice_number', textType),
    Column('invoice_date', timestampType),
    Column('due_date', timestampType),
    Column('state', textType),
    Column('amount_total', integerType),
    Column('amount_residual', integerType),
    Column('tax_amount', integerType),
    Column('create_date', timestampType),
    Column('write_date', timestampType),
  ]),
  Table('account_payment', [
    Column('id', uuidType),
    Column('company_id', uuidType),
    Column('invoice_id', uuidType),
    Column('partner_id', uuidType),
    Column('currency_id', uuidType),
    Column('amount', integerType),
    Column('payment_date', timestampType),
    Column('payment_method', textType),
    Column('transaction_id', textType),
    Column('state', textType),
    Column('create_date', timestampType),
    Column('write_date', timestampType),
  ]),
]);
